### ISSUE TITLE
attachment (packageName prefix) error 

### ISSUE THREAD

**Issue by y00437830** [artipie/npm-adapter#23] opened 2020-02-28 06:16 UTC
When attachment contains a multi-level directory, like
`@demo1/aabcc-2.0.0.tgz`, `Key.string` is called in
`storage.save()`, and the method part does not allow "/".
I remembered the `@scope` cause another issue in the last month.
So please test our project by `@scope/name.tgz` type in the future.

Sorry, I cannot show the detail picture in gitlab, since the Huawei network security proxy 
I will contact you through espace.

**Comment by 0crat** [comment] 2020-02-28 06:16
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2020-02-28 06:16
@y00437830[/z](https://www.0crat.com/u/y00437830) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2020-02-28 06:58
@0crat assign @Sammers21

**Comment by 0crat** [comment] 2020-02-28 07:19
> @0crat assign @Sammers21  ([here](https://github.com/artipie/npm-adapter/issues/23#issuecomment-592364918))

@g4s8 Thanks for your contribution, @y00437830[/z](https://www.0crat.com/u/y00437830)! If you would be a member of [the project](https://www.0crat.com/p/CT2E6TK9B), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2020-02-28 07:20
> @0crat assign @Sammers21  ([here](https://github.com/artipie/npm-adapter/issues/23#issuecomment-592364918))

@g4s8 The job [#23](https://github.com/artipie/npm-adapter/issues/23) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fff94fce-6d3b-4b06-8b05-3c2dc8958c05); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-02-28 07:53
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment] 2020-03-03 12:07
@Sammers21 did you managed to solve this issue?

**Comment by Sammers21** [comment] 2020-03-03 12:21
@g4s8 , no. @y00437830 , issue description is not clear. I can't understand what is meant.

**Comment by g4s8** [comment] 2021-01-27 08:34
@y00437830 this issues seems to be outdated, since we've added integration tests with scopes and didn't reproduce such issue. Please submit a new bug in case if you still have an issue.

**Closed by g4s8** 2021-01-27 08:34 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2021-01-27 09:00
Job `gh:artipie/npm-adapter#23` is not assigned, can't get performer
