### ISSUE TITLE
Fix tests disabled in #88 PR

### ISSUE THREAD

**Issue by Sammers21** [artipie/npm-adapter#89] opened 2020-07-17 10:46 UTC
Some tests have been disabled for the proxy module in #88 PR during asto/http module migration process. The occurred problems should be investigated and fixed.

**Comment by marceloamadeu** [comment] 2020-07-21 16:33
@0crat refuse

**Comment by marceloamadeu** [comment] 2020-07-22 14:18
@0crat status

**Comment by 0crat** [comment] 2020-07-22 15:59
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by marceloamadeu** [comment] 2020-07-23 18:40
@0crat refuse

**Comment by marceloamadeu** [comment] 2020-08-05 16:03
@0crat status

**Comment by 0crat** [comment] 2020-10-09 09:35
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I see that you unassigned this issue; the order is still assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment] 2020-10-09 09:35
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Closed** 2020-10-20 09:18 UTC
Labels: 0crat/role/DEV, 0crat/scope, bug

**Comment by 0crat** [comment] 2020-10-20 10:23
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @Sammers21 (its creator); I won't close the order; please, re-open it and ask @Sammers21 to close it
