### ISSUE TITLE
com.artipie.npm.TgzRelativePath#curlWithoutScope and curlWithScope regex error

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#30] opened 2020-03-05 05:39 UTC
When uploading a file via crul, the url contains version information
you can change the following 2 unit test debugging
@Test
    public void curlWithScopeIdentifiedCorrectly() {
        MatcherAssert.assertThat(
            new TgzRelativePath("http://localhost:8080/artifactory/api/npm/npm-test-local-1/@scope/yuanye05/1.0.3/yuanye05-1.0.3.tgz").relative(),
            new IsEqual<>("@scope/yuanye05/1.0.3/yuanye05-1.0.3.tgz")
        );
   }
 @Test
    public void curlWithoutScopeIdentifiedCorrectly() {
        MatcherAssert.assertThat(
            new TgzRelativePath("http://localhost:8080/artifactory/api/npm/npm-test-local-1/yuanye05/1.0.3/yuanye05-1.0.3.tgz").relative(),
            new IsEqual<>("yuanye05/1.0.3/yuanye05-1.0.3.tgz")
        );
    }

**Comment by 0crat** [comment] 2020-03-05 05:39
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Sammers21** [comment] 2020-03-12 11:54
@dingdaoyi , what do you mean?

**Comment by Sammers21** [comment] 2020-03-12 11:54
@dingdaoyi , what is the issue?

**Comment by g4s8** [comment] 2021-01-27 08:36
@dingdaoyi closing as duplicate of #169

**Closed by g4s8** 2021-01-27 08:36 UTC

**Comment by 0crat** [comment] 2021-01-27 09:05
Job `gh:artipie/npm-adapter#30` is not assigned, can't get performer
